[package]
name = "langmer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
chrono = { version = "0.4.26", features = ["serde"] }
diesel = { version = "2.1.0", features = ["sqlite", "chrono"] }
dotenvy = "0.15"
serde = { version = "1.0.179", features = ["derive"] }
serde_json = "1.0.104"
futures = "0.3"
garde = "0.13.0"
